### ISSUE TITLE
What is Axbo using to "learn" the sleep pattern? 

### ISSUE THREAD

**Issue by triNem** [jansolo/aXbo-research#10]
Hello Jansolo I wondered whether you had seen the new question in the original post. Just in case I am reposting...

<h4>What is Axbo using to "learn" the sleep pattern? 

I read at [axbo.zendesk.com](https://axbo.zendesk.com/hc/en-us/articles/200605313-aXbo-wake-me-up-at-the-last-time-with-a-Pip-tone) that Axbo "learns" the sleep pattern over a few days. 

What are the criteria used to learn this sleep pattern ? If neither the logs nor the clock settings are  influencing the waking hour then what is there to learn ?

This seems important since this might influence the way I sleep (e.g. keeping a regular sleep rhythm for instance). Also, I have an old Axbo that no longer uses it's batteries. It seems to be less efficient at waking me up ever since this happened...

**Comment by jansolo** [comment]
Hi triNem,

I am sorry, but I can not help you with this question. Because I do not know, how the internals of aXbo work. I just developed the aXbo research software ;)

But if you like more information, I can connect you with the inventor of aXbo, who is a close friend of mine - and a very friendly guy.

**Comment by Jerberus** [comment]
triNem, 

You can replace the batteries inside with 3AAA rechargeable batteries (make sure they're the same technology - I think NiMH).  I also saw there's a video posted on it: https://www.youtube.com/watch?v=aiqkQEz7jTU

**Comment by triNem** [comment]
<h6>@jansolo 
Thank you. I'd love to get in touch with the inventor. Axbo is a great device. Understanding it's functionalities should be very rewarding. 
Here is a temporary email (you should remove all the spaces) :
syn 89v @ hushmail. com

<h6>@Jerberus
Thank you. I tried playing with the batteries but my problem seems to be more complex (hardware related, I guess) : The device can recharge the batteries but it fails to use their power. This means that it looses data if it gets unplugged. That's the reason why I noticed the learning pattern...

**Comment by jansolo** [comment]
@triNem e-mail send. I will close the issue.
