### ISSUE TITLE
License of the aXbo-research source code

### ISSUE THREAD

**Issue by aszlig** [jansolo/aXbo-research#8]
What are the terms/licensing of this package, especially if it comes to inclusion into distributions?
I've found [licensing information](https://github.com/jansolo/aXbo-research/blob/de11bded2336c441ebe5050d80ce583011bc4459/aXbo-research/resource/license/NOTICE.txt) for the various bundled libraries, but haven't found anything related to the project itself.

**Comment by aszlig** [comment]
@jansolo: Ping?

**Comment by jansolo** [comment]
Sorry, forgot about that. I did not think about the right license yet. I do not care about it very much either ;)

So any license that allows redistribution, inclusion and/or modification of the sources or the binaries without the requirement to redistribute the source should be fine for me. Any recommendations?

**Comment by aszlig** [comment]
Well, if you want your project to stay free and disallow usage of your source code to be included in proprietary programs, I'd strongly suggest a copyleft license such as the (A)GPL, see http://www.gnu.org/licenses/licenses.html.

If you really don't care, something like the Apache License, see here: http://www.apache.org/licenses/#2.0

But as said, this will allow others to make derivative works of your code without the need to release their changes.

**Comment by jansolo** [comment]
Ok, thanks for clarification. I will check with the inventor of aXbo, which option he prefers and add the corresponding license soon. Personally I'd prefer the second option.
